# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "G-5B1DXP49YM"

baseURL = "//ramanlab.github.io/SysBioBook/"
# baseURL = "/"
languageCode = "en-us"
title = "An Introduction to Computational Systems Biology"
publishDir = "docs"

[params]
  BookLogo = 'logo.png'
  BookSection = '*'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
