baseURL = "//ramanlab.github.io/SysBioBook/"
# baseURL = "/"
languageCode = "en-us"
title = "An Introduction to Computational Systems Biology"
publishDir = "docs"

[params]
  BookLogo = 'logo.png'
  BookSection = '*'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true